apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: bmi-app
    env: {{ .Values.env }}
  name: bmi-app-{{ .Values.env }}
  annotations:
      argocd-image-updater.argoproj.io/image-list: myimage=mohammadkhoshnazar/bmi-calc
      argocd-image-updater.argoproj.io/myimage.update-strategy: latest
      argocd-image-updater.argoproj.io/myimage.allow-tags: any
      argocd-image-updater.argoproj.io/write-back-method: git
spec:
  replicas: 3
  selector:
    matchLabels:
      app: bmi-app
      env: {{ .Values.env }}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: bmi-app
        env: {{ .Values.env }}
    spec:
      containers:
      - image: {{ .Values.image.repository }}
        name: {{ .Chart.Name }}
        ports:
        - containerPort: 3000
        resources: {}
status: {}