apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: bmi-app
    env: {{ .Values.env }}
  name: bmi-app-{{ .Values.env }}
spec:
  replicas: 3
  selector:
    matchLabels:
      app: bmi-app
      env: {{ .Values.env }}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: bmi-app
        env: {{ .Values.env }}
    spec:
      containers:
      - image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        name: {{ .Chart.Name }}
        ports:
        - containerPort: 3000
        resources: {}
status: {}




####### Annotations for ArgoCD image updater
# argocd-image-updater.argoproj.io/bmi.update-strategy=latest 
# argocd-image-updater.argoproj.io/git-branch=master 
# argocd-image-updater.argoproj.io/image-list=bmi=mohammadkhoshnazar/bmi-calc 
# argocd-image-updater.argoproj.io/write-back-method=git:secret:argo/git-creds