apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: bmi-app
    env: {{ .Values.env }}
  name: bmi-app-{{ .Values.env }}
spec:
  replicas: 3
  selector:
    matchLabels:
      app: bmi-app
      env: {{ .Values.env }}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: bmi-app
        env: {{ .Values.env }}
    spec:
      containers:
      - image: {{ .Values.image }}
        name: {{ .Chart.Name }}
        ports:
        - containerPort: 3000
        resources: {}
status: {}