apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-{{ .Values.env }}-svc
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    env: {{ .Values.env }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.externalPort }}
    targetPort: {{ .Values.service.internalPort }}
    protocol: TCP
    name: {{ .Values.service.name }}
  selector:
    app: {{ .Chart.Name }}
    env: {{ .Values.env }}