helm:
  parameters:
  - name: ingress.hosts.host
    value: testapp.rytle-it.de
    forcestring: false
  - name: image.name
    value: mohammadkhoshnazar/bmi-calc
    forcestring: true
  - name: image.tag
    value: v1
    forcestring: true
